# Generated by Django 2.2.9 on 2020-09-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctj_nombre', models.CharField(max_length=150)),
                ('ctj_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de trabajo',
            },
        ),
        migrations.CreateModel(
            name='TypeJob',
            fields=[
                ('tp_codigo', models.AutoField(db_column='tp_codigo', primary_key=True, serialize=False)),
                ('tp_nome', models.CharField(max_length=150)),
                ('tp_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('j_codigo', models.AutoField(db_column='j_codigo', primary_key=True, serialize=False)),
                ('j_nombre', models.CharField(max_length=150)),
                ('j_companyname', models.CharField(max_length=150)),
                ('j_url', models.CharField(max_length=150)),
                ('j_description', models.TextField()),
                ('j_email', models.CharField(max_length=80)),
                ('j_position_ordem', models.IntegerField()),
                ('j_position_location', models.CharField(max_length=80)),
                ('CategoriaJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.CategoriaJob')),
                ('TypeJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.TypeJob')),
            ],
            options={
                'verbose_name': 'Job',
            },
        ),
    ]
